# Generated by Django 3.0.8 on 2020-07-27 06:35

from django.db import migrations, connection


def load_data_from_sql(apps, schema_editor):
    import os
    file_path = os.path.join(os.path.dirname(__file__), 'kerapido.sql')
    sql_statement = open(file_path, encoding="utf8").read()
    with connection.cursor() as c:
        c.executescript(sql_statement)


class Migration(migrations.Migration):

    dependencies = [
        ('kerapido', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data_from_sql),
    ]
