
INSERT INTO kerapido_provincia (nombre) VALUES ('Pinar del Río');
INSERT INTO kerapido_provincia (nombre) VALUES ('Artemisa');
INSERT INTO kerapido_provincia (nombre) VALUES ('Mayabeque');
INSERT INTO kerapido_provincia (nombre) VALUES ('La Habana');
INSERT INTO kerapido_provincia (nombre) VALUES ('Matanzas');
INSERT INTO kerapido_provincia (nombre) VALUES ('Villa Clara');
INSERT INTO kerapido_provincia (nombre) VALUES ('Cienfuegos');
INSERT INTO kerapido_provincia (nombre) VALUES ('Sancti Spíritus');
INSERT INTO kerapido_provincia (nombre) VALUES ('Ciego de Ávila');
INSERT INTO kerapido_provincia (nombre) VALUES ('Camagüey');
INSERT INTO kerapido_provincia (nombre) VALUES ('Las Tunas');
INSERT INTO kerapido_provincia (nombre) VALUES ('Holguín');
INSERT INTO kerapido_provincia (nombre) VALUES ('Granma');
INSERT INTO kerapido_provincia (nombre) VALUES ('Santiago de Cuba');
INSERT INTO kerapido_provincia (nombre) VALUES ('Guantánamo');
INSERT INTO kerapido_provincia (nombre) VALUES ('Isla de la Juventud');

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Pinar del Río', 1);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Consolación del Sur', 1);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('San Juan y Martínez', 1);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Los Palacios', 1);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Sandino', 1);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Guane', 1);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('La Palma', 1);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('San Luis', 1);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Minas de Matahambre', 1);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Viñales', 1);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Mantua', 1);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Artemisa', 2);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('San Cristóbal', 2);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('San Antonio', 2);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Bauta', 2);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Bahía Honda', 2);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Mariel', 2);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Caimito', 2);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Güira de Melena', 2);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Alquízar', 2);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Guanajay', 2);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Candelaria', 2);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('San José de las Lajas', 3);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Güines', 3);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Santa Cruz del Norte', 3);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Madruga', 3);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Quivicán', 3);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Bejucal', 3);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Batabanó', 3);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Jaruco', 3);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Nueva Paz', 3);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('San Nicolás', 3);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Melena del Sur', 3);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Diez de Octubre', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Arroyo Naranjo', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Boyeros', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Playa', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Habana del Este', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('San Miguel del Padrón', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Plaza de la Revolución', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Centro Habana', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Marianao', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('La Lisa', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Cerro', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Guanabacoa', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Habana Vieja', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Cotorro', 4);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Regla', 4);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Matanzas', 5);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Cárdenas', 5);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Colón', 5);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Jagüey Grande', 5);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Jovellanos', 5);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Unión de Reyes', 5);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Pedro Betancourt', 5);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Perico', 5);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Calimete', 5);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Limonar', 5);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Los Arabos', 5);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Marti', 5);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Ciénaga de Zapata', 5);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Santa Clara', 6);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Manicaragua', 6);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Placetas', 6);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Camajuaní', 6);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Ranchuelo', 6);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Sagua la Grande', 6);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Santo Domingo', 6);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Remedios', 6);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Caibarién', 6);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Encrucijada', 6);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Cifuentes', 6);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Corralillo', 6);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Quemado de Güines', 6);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Cienfuegos', 7);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Cumanayagua', 7);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Rodas', 7);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Palmira', 7);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Aguada de Pasajeros', 7);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Cruces', 7);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Abreus', 7);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Lajas', 7);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Sancti Spíritus', 8);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Trinidad', 8);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Cabaiguán', 8);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Yaguajay', 8);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Jatibonico', 8);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Taguasco', 8);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Fomento', 8);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('La Sierpe', 8);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Ciego de Ávila', 9);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Morón', 9);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Chambas', 9);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Baraguá', 9);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Ciro Redondo', 9);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Primero de Enero', 9);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Venezuela', 9);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Majagua', 9);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Florencia', 9);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Bolivia', 9);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Camagüey', 10);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Florida', 10);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Guáimaro', 10);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Vertientes', 10);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Santa Cruz del Sur', 10);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Nuevitas', 10);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Minas', 10);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Sibanicú', 10);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Esmeralda', 10);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Carlos Manuel de Céspedes', 10);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Jimaguayú', 10);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Sierra de Cubitas', 10);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Najasa', 10);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Las Tunas', 11);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Puerto Padre', 11);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Jesús Menéndez', 11);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Jobabo', 11);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Majibacoa', 11);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Amancio', 11);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Colombia', 11);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Manatí', 11);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Holguín', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Mayarí', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Banes', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Moa', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Gibara', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Calixto García', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Báguanos', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Rafael Freyre', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Sagua de Tánamo', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Urbano Noris', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Cacocúm', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Cueto', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Frank País', 12);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Antilla', 12);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Bayamo', 13);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Manzanillo', 13);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Jiguaní', 13);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Yara', 13);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Bartolomé Masó', 13);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Guisa', 13);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Río Cauto', 13);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Campechuela', 13);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Niquero', 13);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Media Luna', 13);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Buey Arriba', 13);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Pilón', 13);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Cauto Cristo', 13);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Santiago de Cuba', 14);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Palma Soriano', 14);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Contramaestre', 14);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Songo - La Maya', 14);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('San Luis', 14);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Segundo Frente', 14);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Mella', 14);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Guamá', 14);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Tercer Frente', 14);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Guantánamo', 15);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Baracoa', 15);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('El Salvador', 15);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Maisí', 15);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('San Antonio del Sur', 15);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Imías', 15);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Yateras', 15);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Niceto Pérez', 15);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Manuel Tames', 15);
INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Caimanera', 15);

INSERT INTO kerapido_municipio (nombre, provincia_id) VALUES ('Isla de la Juventud', 16);

INSERT INTO kerapido_servicio (nombre, descripcion) VALUES ('Servicio domicilio', 'Entrega de productos hasta el lugar donde se encuentra el cliente');
INSERT INTO kerapido_servicio (nombre, descripcion) VALUES ('Servicio recogida', 'Servicio de recogida de producto en el lugar');
INSERT INTO kerapido_servicio (nombre, descripcion) VALUES ('VIP', 'Reservación de mesas o espacios');